#!/usr/bin/env bash
# Render local Caddy templates into portable/home-stack/Caddyfile.
# Use LOCAL_HTTP=1 or LOCAL_TLS=1 for local development modes.
# Production Caddyfile is generated by `hs sync` from the registry.
set -euo pipefail

echo "Rendering local Caddyfile..."
SCRIPT_DIR="$(cd -- "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$SCRIPT_DIR/lib/common.sh"
home_stack_load_env
ROOT_DIR="$HOME_STACK_BUNDLE_DIR"
TEMPLATE_LOCAL="$HOME_STACK_TEMPLATE_DIR/Caddyfile.local.template"
TEMPLATE_TLS_LOCAL="$HOME_STACK_TEMPLATE_DIR/Caddyfile.local-tls.template"
OUT="$HOME_STACK_BUNDLE_DIR/Caddyfile"

if [[ "${LOCAL_TLS:-0}" == "1" ]] && [[ -f "$TEMPLATE_TLS_LOCAL" ]]; then
  home_stack_render_template "$TEMPLATE_TLS_LOCAL" "$OUT"
  echo "Wrote local TLS Caddyfile to $OUT"
elif [[ "${LOCAL_HTTP:-0}" == "1" ]] && [[ -f "$TEMPLATE_LOCAL" ]]; then
  home_stack_render_template "$TEMPLATE_LOCAL" "$OUT"
  echo "Wrote local (HTTP) Caddyfile to $OUT"
else
  echo "No local mode selected (LOCAL_HTTP=1 or LOCAL_TLS=1)." >&2
  echo "For production, run 'hs sync' to generate the Caddyfile from the registry." >&2
  exit 1
fi
